# run:
# docker-compose -p united up -d

# PYG-DATA-COLLECTOR

datacollector:
  build: .
  ports:
      - "3000:3000"
  restart: always
  environment:
    - 'EMAIL_ADDRESS=citanienadnes@gmail.com'
    - 'EMAIL_PASSWORD=***CHANGE-ME****'
    - 'MONGO_DB_CONNECTION=***CHANGE-ME****'
    - PORT=3000